# Abstract für Gleichstellungsplan

## Zentrales Element: Zuordnung von Geschlecht über "Gender-Guesser", Manuelle Nachbearbeitung für MPG-Angehörige zur Korrektur der automatisierten Zuordnungen und manuelle Anreicherung mit Positionen

In [1]:
# Zentrale Komponente: Gender-Guesser - Installation über pip nur inital nötig 
#!pip install gender-guesser

In [1]:
import gender_guesser.detector as gender
import pandas as pd
import numpy as np
import re
import pdb
from collections import defaultdict

In [2]:
# Defintion der Funktion für Gendererkennung, die an ansprechender Stelle aufgerufen wird

def get_gender(name):                        
  d = gender.Detector()
  return d.get_gender(name)

# Daten aus Openrefine

### Wichtig, dass die Daten zunächst in Openrefine eingelesen werden, da das JSON sonst für Python nicht verarbeitbar ist!   

Es macht ggf. Sinn, einen Gesamtextrakt zu ziehen, um dann per Skript die für den Bericht relevanten Daten zu holen?

In [3]:
# Einlesen der Date aus dem Notebook "PuRe Rohdatenextrakt.jpynb"
df_pure = pd.read_excel('Daten/df_pure.xlsx')

# Zur Sicherheit die Anzahl an IDs = Datensätzen zählen
df_pure['90999_ItemID'].nunique()

447

In [4]:
# Reduzierung auf die für die Analyse relevanten Spalten 

df_glp = df_pure[['1002_Genre',
                  '1_Nachname',
                  '2_Vorname',
                  'Name',
                  '4_Cone',
                  '5_Affiliation',
                  '1101_Quellentitel',
                  '1103_Ersterscheinungsdatum',
                  '90999_ItemID']]

In [5]:
# Aufbereitung der Daten zur Gendererkennung (läuft über die Vornamen)

df_vorname = df_glp[['2_Vorname', 'Name', '4_Cone']]    # Nur die Spalten mit den Vornamen und Item-IDs für die Gendererkennung
df_vorname = df_vorname.drop_duplicates()           # Duplikate entfernen, damit jeder Vorname nur einmal vorkommt
df_vorname = df_vorname.dropna()                    # Entfernen aller Zeilen mit fehlenden Vornamen / Cone-IDs, da diese für die Gendererkennung nicht relevant sind

df_vorname['3_Gender'] = df_vorname['2_Vorname'].apply(get_gender) # Hier Aufruf der Gender-Erkennungsfunktion

In [6]:
# Erster Eindruck der Zuordnungen, zeigt auch Fehler oder Unsicherheiten an 

gender_counts = df_vorname['3_Gender'].value_counts()
gender_counts

3_Gender
male           55
female         41
unknown        24
mostly_male     1
andy            1
Name: count, dtype: int64

In [7]:
# Liste wird erzeugt zur Prüfung und manuellen Nachbereitung 

# Zuerst Zusammenführung der ursprünglichen Personendaten mit Genderinformationen
df_personen = df_glp[['Name', '4_Cone']]
df_personenliste_gendered = pd.merge(df_personen, df_vorname[['Name', '3_Gender']], on='Name', how='left')  

# Neue Liste, die für die manuelle Nachbarbeitung genutzt wird  
df_personenliste_gendered.dropna(subset=['Name'], inplace=True)  #Leerzeilen löschen 
df_personenliste_gendered.drop_duplicates(inplace=True)
df_personenliste_gendered['6_Status'] = None             #einfügen einer leeren Spalte für die Statusinfos

# Reduzierung auf die Personen mit Cone-Eintrag
only_cone = ['CONE']  
df_personenliste_cropped = df_personenliste_gendered[df_personenliste_gendered['4_Cone'].isin(only_cone)]
df_personenliste_cropped.to_excel('Daten/Pure_Personen_gendered.xlsx', index=False) # Export für Excel

# Bearbeitungsschritte der Datei "Pure_Personen_gendered.xlsx":  


1. Prüfung der korrekten Geschlechterzuordnung (auf alle Fälle für die Personen mit Cone-ID, also Institutszugehörigkeit)   
2. Hinzufügen des Status nach folgendem Schema

- Doctoral Student
- Postdoc
- Senior Researcher
- Research Group Leader
- Director
- Director emeritus
- Visiting Researcher
- Other

### Nach Fertigstellung Datei wieder hochladen!

In [8]:
# Achtung, dass der Name der Eingabedatei stimmt!
df_personenliste_gendered_korr = pd.read_excel('Daten/Pure_Personen_gendered.xlsx')

# Extrakt der relevanten Spalten
df_gender = df_personenliste_gendered_korr[['Name', '3_Gender','6_Status']]

# Datei in das Hauptdatenframe einspielen
merged_df = pd.merge(df_glp, df_gender[['Name', '3_Gender', '6_Status']], on='Name', how='left')

In [9]:
# Dublikate Entfernen
merged_df.drop_duplicates(inplace=True) 

#Kontrollfrage, ob es sich immer noch um die gleiche Anzahl Titel handelt
merged_df['90999_ItemID'].nunique()

447

In [10]:
df_glp_cleaned = merged_df.rename(columns={
    '1002_Genre':'Genre',
    '1103_Ersterscheinungsdatum' : 'Datum',
    '1_Nachname':'Nachname',
    '2_Vorname' : 'Vorname',
    '3_Gender':'Gender',
    '4_Cone':'Cone',
    '6_Status' : 'Status',
    '5_Affiliation':'Affiliation',
    '90999_ItemID' : 'ItemID' }) 

df_glp_cleaned

,Genre,Nachname,Vorname,Name,Cone,Affiliation,1101_Quellentitel,Datum,ItemID,Gender,Status
0,ARTICLE,Polyák,Pálma,Pálma Polyák,CONE,"Politische Ökonomie, MPI for the Study of Soci...",Review of International Political Economy,2026.0,item_3705309,female,Senior Researcher
1,ARTICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,item_3705309,NaN,NaN
3,ARTICLE,Cigna,Luca,Luca Cigna,CONE,"Politische Ökonomie, MPI for the Study of Soci...",New Political Economy,2026.0,item_3699285,male,Postdoc
4,ARTICLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,item_3699285,NaN,NaN
6,ARTICLE,Lopez-Uroz,Nina,Nina Lopez-Uroz,CONE,Umstrittene Ökologien in kapitalistischen Demo...,NaN,NaN,item_3699285,female,Postdoc
...,...,...,...,...,...,...,...,...,...,...,...
2331,CONTRIBUTION_TO_COLLECTED_EDITION,NaN,NaN,NaN,NaN,NaN,RIPE Series in Global Political Economy,NaN,item_3484993,NaN,NaN
2332,CONTRIBUTION_TO_HANDBOOK,Maccarrone,Vincenzo,Vincenzo Maccarrone,NaN,"University College Dublin, Ireland",The Routledge Handbook of the Gig Economy,2022.0,item_3458140,NaN,NaN
2333,CONTRIBUTION_TO_HANDBOOK,Tassinari,Arianna,Arianna Tassinari,CONE,"Politische Ökonomie, MPI for the Study of Soci...",NaN,NaN,item_3458140,female,Senior Researcher
2334,CONTRIBUTION_TO_HANDBOOK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,item_3458140,NaN,NaN
2336,CONTRIBUTION_TO_HANDBOOK,NaN,NaN,NaN,NaN,NaN,Routledge International Handbooks,NaN,item_3458140,NaN,NaN

In [16]:
# Alle Zeilen löschen, in denen kein Name vorhanden ist 
before = len(df_glp_cleaned)
mask = df_glp_cleaned['Name'].notna() & (df_glp_cleaned['Name'].astype(str).str.strip() != '')
df_glp_cleaned_rows = df_glp_cleaned[mask].copy()
after = len(df_glp_cleaned_rows)
print(f"Dropped {before - after} rows; remaining {after}")

Dropped 727 rows; remaining 853

In [17]:
df_glp_cleaned_rows['ItemID'].nunique()

447

In [18]:
# Datumsspalte bereinigen, da durch Excel-Export verändert und Werte auffüllen
df_glp_cleaned_rows['Datum'] = df_glp_cleaned_rows['Datum'].astype(str).str.extract(r'(\d{4})')
df_glp_cleaned_rows['Datum'] = df_glp_cleaned_rows['Datum'].ffill() 

# Spalteninhalt wieder als Zahl definieren
df_glp_cleaned_rows['Datum'] = df_glp_cleaned_rows['Datum'].astype(int)

# Blick auf die enthaltenen Daten
df_glp_cleaned_rows['Datum'].unique()

array([2026, 2025, 2024, 2023, 2017, 2022, 2020, 2021])

# Welche(s) Jahr(e), hier definieren:

In [19]:
years = [2023, 2024, 2025]   # oder bei einem Einzahljahr so [2025]

df_matching_years = df_glp_cleaned_rows[df_glp_cleaned_rows['Datum'].isin(years)].copy()

In [26]:
df_not_matching_years = df_glp_cleaned_rows[df_glp_cleaned_rows['Datum'].isin(years) == False].copy()
df_not_matching_years.to_excel('Daten/GLP_nicht_passende_Jahre.xlsx', index=False)

In [24]:
# Hinzufügen eines Zeilenzählers für die einzelnen IDs 
df_matching_years['Item_seq'] = df_matching_years.groupby('ItemID').cumcount() + 1

In [27]:
# Ausgangsdatei für alles weitere, Name wieder zurück auf df 
df_matching_years.to_excel('Daten/GLP_passende_Jahre.xlsx', index=False)
df = df_matching_years

In [ ]:
# für ggf. Nutzung in PuRE Anzeige der ItemIds, diese kann man nämlich in der Form (item_3600598 item_3599827 item_3562810 item_3596887) direkt in Suche in Pure eingeben - wenn es zu viele Datensätze sind klappt es nicht. 312 hat geklappt!
df_matching_years['ItemID'].unique()

array(['item_3674340', 'item_3674550', 'item_3693171', 'item_3598030',
       'item_3637800', 'item_3580346', 'item_3580322', 'item_3677588',
       'item_3677585', 'item_3677583', 'item_3561936', 'item_3598241',
       'item_3598226', 'item_3598214', 'item_3605323', 'item_3638367',
       'item_3669835', 'item_3668922', 'item_3521755', 'item_3524850',
       'item_3521777', 'item_3508417', 'item_3693194', 'item_3693350',
       'item_3695172', 'item_3691588', 'item_3692950', 'item_3695187',
       'item_3693118', 'item_3693451', 'item_3636908', 'item_3658976',
       'item_3658141', 'item_3695418', 'item_3626875', 'item_3625347',
       'item_3695165', 'item_3695146', 'item_3663967', 'item_3677417',
       'item_3677412', 'item_3677403', 'item_3693143', 'item_3507188',
       'item_3692913', 'item_3692622', 'item_3692455', 'item_3547744',
       'item_3688842', 'item_3691594', 'item_3600748', 'item_3656833',
       'item_3688937', 'item_3685535', 'item_3649640', 'item_3656743',
       'item_3683675', 'item_3683852', 'item_3688898', 'item_3620099',
       'item_3655164', 'item_3684347', 'item_3683402', 'item_3685137',
       'item_3685127', 'item_3685120', 'item_3683506', 'item_3683642',
       'item_3679614', 'item_3683887', 'item_3684109', 'item_3683864',
       'item_3674609', 'item_3619275', 'item_3526834', 'item_3619197',
       'item_3683533', 'item_3663990', 'item_3647761', 'item_3599946',
       'item_3599909', 'item_3592635', 'item_3664826', 'item_3679064',
       'item_3521776', 'item_3637785', 'item_3581898', 'item_3602592',
       'item_3572471', 'item_3601892', 'item_3629546', 'item_3669418',
       'item_3669811', 'item_3644441', 'item_3587930', 'item_3675121',
       'item_3654991', 'item_3655005', 'item_3591696', 'item_3613473',
       'item_3677211', 'item_3676724', 'item_3675876', 'item_3583861',
       'item_3629968', 'item_3673525', 'item_3643899', 'item_3583998',
       'item_3602552', 'item_3590090', 'item_3599580', 'item_3615902',
       'item_3672074', 'item_3662096', 'item_3667757', 'item_3671892',
       'item_3660819', 'item_3651650', 'item_3592080', 'item_3521774',
       'item_3521757', 'item_3521761', 'item_3521771', 'item_3521756',
       'item_3553952', 'item_3670909', 'item_3669818', 'item_3669384',
       'item_3668916', 'item_3668793', 'item_3656885', 'item_3656849',
       'item_3608821', 'item_3612794', 'item_3611034', 'item_3630921',
       'item_3660803', 'item_3660810', 'item_3663932', 'item_3658895',
       'item_3660793', 'item_3618904', 'item_3610392', 'item_3610388',
       'item_3662393', 'item_3662118', 'item_3608155', 'item_3608143',
       'item_3659142', 'item_3658983', 'item_3657878', 'item_3658788',
       'item_3658343', 'item_3657861', 'item_3583816', 'item_3657724',
       'item_3657683', 'item_3657657', 'item_3657652', 'item_3657031',
       'item_3647439', 'item_3508467', 'item_3654632', 'item_3615838',
       'item_3652020', 'item_3656242', 'item_3656101', 'item_3655087',
       'item_3654976', 'item_3654668', 'item_3655196', 'item_3589729',
       'item_3654980', 'item_3626554', 'item_3626761', 'item_3651218',
       'item_3641462', 'item_3641455', 'item_3652821', 'item_3652816',
       'item_3652807', 'item_3652461', 'item_3642616', 'item_3650008',
       'item_3649609', 'item_3636610', 'item_3641449', 'item_3651466',
       'item_3651458', 'item_3651446', 'item_3640287', 'item_3649455',
       'item_3633697', 'item_3649194', 'item_3649471', 'item_3529955',
       'item_3527142', 'item_3644198', 'item_3647680', 'item_3613263',
       'item_3647584', 'item_3512263', 'item_3643086', 'item_3594839',
       'item_3594829', 'item_3626253', 'item_3626245', 'item_3621813',
       'item_3640018', 'item_3581928', 'item_3561692', 'item_3516742',
       'item_3523578', 'item_3642106', 'item_3641738', 'item_3638356',
       'item_3638011', 'item_3556633', 'item_3634672', 'item_3536755',
       'item_3616909', 'item_3616902', 'item_3634703', 'item_3547544',
       'item_3588529', 'item_3596640', 'item_3608102', 'item_3592769',
       'item_3569462', 'item_3561722', 'item_3553881', 'item_3634093',
       'item_3562131', 'item_3630246', 'item_3629669', 'item_3632001',
       'item_3627928', 'item_3632027', 'item_3582244', 'item_3603051',
       'item_3631744', 'item_3588187', 'item_3630264', 'item_3589018',
       'item_3619182', 'item_3626583', 'item_3622597', 'item_3557326',
       'item_3562291', 'item_3622653', 'item_3588908', 'item_3618021',
       'item_3516205', 'item_3621273', 'item_3621052', 'item_3621267',
       'item_3552217', 'item_3619580', 'item_3617373', 'item_3618758',
       'item_3528744', 'item_3619232', 'item_3607729', 'item_3547643',
       'item_3612746', 'item_3612766', 'item_3618882', 'item_3618756',
       'item_3614737', 'item_3618050', 'item_3608561', 'item_3512766',
       'item_3615914', 'item_3575111', 'item_3587225', 'item_3512000',
       'item_3531845', 'item_3512395', 'item_3492350', 'item_3612897',
       'item_3601901', 'item_3521606', 'item_3516445', 'item_3513921',
       'item_3527750', 'item_3489209', 'item_3501133', 'item_3529165',
       'item_3532013', 'item_3515835', 'item_3505953', 'item_3561984',
       'item_3562826', 'item_3510300', 'item_3490194', 'item_3552327',
       'item_3562101', 'item_3584124', 'item_3561998', 'item_3573422',
       'item_3552059', 'item_3515375', 'item_3563724', 'item_3570107',
       'item_3609424', 'item_3580677', 'item_3606347', 'item_3598949',
       'item_3518335', 'item_3515655', 'item_3601104', 'item_3600601',
       'item_3600598', 'item_3599827', 'item_3562810', 'item_3596887',
       'item_3491807', 'item_3592041', 'item_3590226', 'item_3528712',
       'item_3524998', 'item_3524989', 'item_3589725', 'item_3589126',
       'item_3580263', 'item_3587266', 'item_3584231', 'item_3586698',
       'item_3584740', 'item_3584501', 'item_3584110', 'item_3584102',
       'item_3584006', 'item_3583890', 'item_3490203', 'item_3515465',
       'item_3563675', 'item_3553942', 'item_3573448', 'item_3573535',
       'item_3573456', 'item_3571272', 'item_3571262', 'item_3571157',
       'item_3571219', 'item_3378047', 'item_3527300', 'item_3496301',
       'item_3560962', 'item_3560960', 'item_3559564', 'item_3557167',
       'item_3556666', 'item_3493346', 'item_3552510', 'item_3552477',
       'item_3552331', 'item_3552220', 'item_3551610', 'item_3542158',
       'item_3547342', 'item_3531835', 'item_3542084', 'item_3537272',
       'item_3537261', 'item_3536745', 'item_3509134', 'item_3506276',
       'item_3529172', 'item_3528109', 'item_3527663', 'item_3521775',
       'item_3521768', 'item_3521767', 'item_3521766', 'item_3521765',
       'item_3521763', 'item_3521760', 'item_3521737', 'item_3515352',
       'item_3511194', 'item_3457826', 'item_3507378', 'item_3511568',
       'item_3510188', 'item_3510264', 'item_3509785', 'item_3509795',
       'item_3509636', 'item_3509217', 'item_3508002', 'item_3506542',
       'item_3499054', 'item_3502391', 'item_3502368', 'item_3493276',
       'item_3484988', 'item_3480499', 'item_3484993'], dtype=object)

<hr>

## Kleiner Exkurs zur Ermittlung von Erstautor*innen des Instituts 

# Bitte den Suchstring für eigenes Institut verändern  


(**Bitte beachten:** Das ist nur zur Orientierung, da es angewandt wird auf alle Daten der ausgwählten Jahre, aber noch keine Auswahl des Personenstatus, die noch kommt!)

In [33]:
# Zählung wie viele Einträge es gibt für Personen mit unserer Affiliation und ItemSeq 1, also Er
df_aff = df[df['Cone'].str.contains('CONE', na=False, case=False)]

# Zähler der individuellen ItemIDs in den ausgewählten Daten
all_itemids = df_aff['ItemID'].unique()

# Suche nach Zeilen mit Item_seq 1
itemids_with_seq1 = df_aff[df_aff['Item_seq'] == 1]['ItemID'].unique()

# Ausrechnen der Einträge ohne Item_seq 1
itemids_without_seq1 = set(all_itemids) - set(itemids_with_seq1)

# Und zählen dieser Einträge
count_without_seq1 = len(itemids_without_seq1)

print(f"Gesamtzahl der Datensätze: {len(all_itemids)}")             # Hier sind weniger als für den ausgewählten Zeitraum, was mit kleinen Abweichungen in Affiliations zu tun hat (z.b. auch durch Änderung des Status im Zugehörigkeitszeitraum)
print(f"Datensätze mit MPIfG Erstautor*innen: {len(itemids_with_seq1)}")
print(f"Datensätze bei denen MPIfG Zweit- oder weiterer Autor*in ist: {count_without_seq1}")

Gesamtzahl der Datensätze: 399
Datensätze mit MPIfG Erstautor*innen: 345
Datensätze bei denen MPIfG Zweit- oder weiterer Autor*in ist: 54

In [34]:
# Ansicht der unterschiedlichen vorkommenden Genres
df['Genre'].unique()

array(['ARTICLE', 'CONTRIBUTION_TO_COLLECTED_EDITION', 'BOOK_ITEM',
       'DATA_PUBLICATION', 'EDITORIAL', 'COLLECTED_EDITION', 'THESIS',
       'PREPRINT', 'CONTRIBUTION_TO_HANDBOOK', 'ISSUE', 'BOOK_REVIEW',
       'PAPER', 'CONTRIBUTION_TO_ENCYCLOPEDIA', 'BOOK', 'BLOG_POST',
       'HANDBOOK'], dtype=object)

<hr>

# Falls Status nicht relevant ist, folgen zwei Zeilen und alles für Abzug Statustabelle auskommentieren

In [35]:
# Schritt der Reduzierung auf bestimmte Positionen im Status - da wir beschlossen haben Emeriti, Associates, Visiting und Other rauszulassen

desired_statuses = ['Doctoral Student','Postdoc', 'Senior Researcher','Research Group Leader','Director']
df_final = df[df['Status'].isin(desired_statuses)]

In [ ]:
# Alle Auswahlkriterien sind eingeflossen, jetzt wird die Datei exportiert, falls sie anderweitig genutzt werden soll.
df_final.to_excel('Daten/Rohdaten_GLP.xlsx', index=False)

300

In [59]:
df = df_final # Umbenennung für den Fall, dass Status nicht relevant ist und für den Durchlauf für das weitere Skript

# Statistik

In [ ]:
# Count unique ItemIDs in common dataframes (adjust dataframe name if needed)
def count_unique_itemids(df, col='ItemID'):
    return df[col].nunique()


# Zählung wie viele Einträge es gibt für Personen mit unserer Affiliation und ItemSeq 1, also Er
df_aff = df[df['Cone'].str.contains('CONE', na=False, case=False)]

# Zähler der individuellen ItemIDs in den ausgewählten Daten
all_itemids = df_aff['ItemID'].unique()

# Suche nach Zeilen mit Item_seq 1
itemids_with_seq1 = df_aff[df_aff['Item_seq'] == 1]['ItemID'].unique()

# Ausrechnen der Einträge ohne Item_seq 1
itemids_without_seq1 = set(all_itemids) - set(itemids_with_seq1)

# Und zählen dieser Einträge
count_without_seq1 = len(itemids_without_seq1)

print("Datensätze in eingelesenen Rohdaten:", (df_pure['90999_ItemID'].nunique()))
print("Datensätze nach Bereinigungsschritten:", count_unique_itemids(df_glp_cleaned))
print("Datensätze nach Reduktion auf ausgewählte Jahre:", count_unique_itemids(df_matching_years))
print(f"Gesamtzahl der Datensätze von Autor*innen in der entsprechenden Position: {len(all_itemids)}")             # Hier sind weniger als für den ausgewählten Zeitraum, was mit kleinen Abweichungen in Affiliations zu tun hat (z.b. auch durch Änderung des Status im Zugehörigkeitszeitraum)
print(f"Davon Datensätze mit MPIfG Erstautor*innen: {len(itemids_with_seq1)}")
print(f"Entsprechend: davon Datensätze bei denen MPIfG Zweit- oder weiterer Autor*in ist: {count_without_seq1}")

Datensätze in eingelesenen Rohdaten: 447
Datensätze nach Bereinigungsschritten: 447
Datensätze nach Reduktion auf ausgewählteJahre: 399
Gesamtzahl der Datensätze von Autor*innen in der entsprechenden Position: 300
Davon Datensätze mit MPIfG Erstautor*innen: 246
Entsprechend: davon Datensätze bei denen MPIfG Zweit- oder weiterer Autor*in ist: 54

<hr>

# Abzug für Statustabelle

In [48]:
df_status = df[['Name', 'Gender','Status', 'Genre', 'Datum', 'ItemID']]
df_status

,Name,Gender,Status,Genre,Datum,ItemID
18,Paul Niklas Kullick,male,Doctoral Student,ARTICLE,2025,item_3674340
24,Luca Cigna,male,Postdoc,ARTICLE,2025,item_3674550
28,Donato Di Carlo,male,Senior Researcher,ARTICLE,2025,item_3674550
41,Stephan Gruber,male,Doctoral Student,BOOK_ITEM,2024,item_3598030
49,Benjamin Braun,male,Senior Researcher,DATA_PUBLICATION,2024,item_3580346
...,...,...,...,...,...,...
2280,Björn Bremer,male,Senior Researcher,CONTRIBUTION_TO_HANDBOOK,2023,item_3506542
2290,Lucio Baccaro,male,Director,ARTICLE,2023,item_3502391
2301,Sebastian Kohl,male,Senior Researcher,BLOG_POST,2023,item_3493276
2307,Benjamin Braun,male,Senior Researcher,COLLECTED_EDITION,2023,item_3484988
2327,Benjamin Braun,male,Senior Researcher,CONTRIBUTION_TO_COLLECTED_EDITION,2023,item_3484993

In [49]:
# 1. Zähle Publikationen pro Name
df_status['Number of Publications'] = df_status.groupby('Name')['ItemID'].transform('count')

# 2. Zusammenfassung Publikationen pro Status
summary_per_status = (
    df_status.groupby('Status', as_index=False)
    .agg(
        Publikationen_gesamt=('ItemID', 'count'),
        Female_Authors=('Gender', lambda x: (x == 'female').sum()),
        Male_Authors=('Gender', lambda x: (x == 'male').sum()),
        Divers_Authors=('Gender', lambda x: (x == 'divers').sum())
    )
    .sort_values('Status')
)

# 3. Berechne Prozentanteile für Publikationen pro Status
summary_per_status['Anteil female'] = (
    (summary_per_status['Female_Authors'] / summary_per_status['Publikationen_gesamt']) * 100
).round(0).astype(int)

summary_per_status['Anteil male'] = (
    (summary_per_status['Male_Authors'] / summary_per_status['Publikationen_gesamt']) * 100
).round(0).astype(int)

summary_per_status['Anteil divers'] = (
    (summary_per_status['Divers_Authors'] / summary_per_status['Publikationen_gesamt']) * 100
).round(0).astype(int)

summary_per_status = summary_per_status.round(0) # Zahlen runden

# 4. Zusammenfassung Autorenzahl pro Status
person_gender = df_status.drop_duplicates(subset=['Name', 'Status'])  # Nur ein Eintrag pro Person pro Status


summary_per_status_aut = (
    person_gender.groupby('Status', as_index=False)
    .agg(
        Alle_Personen=('Name', 'nunique'),
        Unique_Female_Authors=('Gender', lambda x: (x == 'female').sum()),
        Unique_Male_Authors=('Gender', lambda x: (x == 'male').sum()),
        Unique_Divers_Authors=('Gender', lambda x: (x == 'divers').sum())
    )
    .sort_values('Status')
)

# 5 Berechnung Prozentanteile für Personen pro Status
summary_per_status_aut['Female_Percent'] = (
    (summary_per_status_aut['Unique_Female_Authors'] / summary_per_status_aut['Alle_Personen']) * 100
).round(0).astype(int)

summary_per_status_aut['Male_Percent'] = (
    (summary_per_status_aut['Unique_Male_Authors'] / summary_per_status_aut['Alle_Personen']) * 100
).round(0).astype(int)

summary_per_status_aut['Divers_Percent'] = (
    (summary_per_status_aut['Unique_Divers_Authors'] / summary_per_status_aut['Alle_Personen']) * 100
).round(0).astype(int)



# 6. Zusammenfügen
overview = summary_per_status_aut.merge(summary_per_status, on='Status', how='left')

#overview

C:\Users\cgmol\AppData\Local\Temp\ipykernel_11360\2311525050.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_status['Number of Publications'] = df_status.groupby('Name')['ItemID'].transform('count')

In [50]:
# Umsortierung und Vereinfachung der Namen, sowie Export zu Excel

overview_sorted = overview[['Status',
                           'Alle_Personen',
                           'Unique_Female_Authors',
                           'Female_Percent',
                           'Unique_Male_Authors',
                           'Male_Percent',
                           'Unique_Divers_Authors',
                           'Divers_Percent',
                           'Publikationen_gesamt',
                           'Female_Authors',
                           'Anteil female',
                           'Male_Authors',
                           'Anteil male',
                           'Divers_Authors',
                           'Anteil divers']]



status_final = overview_sorted.rename(columns={    #Vereinfachung der Spaltennamen
    'Alle_Personen':'Autoren gesamt',
    'Unique_Female_Authors' : 'davon weiblich',
    'Female_Percent':'%-Anteil',
    'Unique_Male_Authors':'davon männlich',
    'Male_Percent': '%-Anteil',
    'Unique_Divers_Authors':'davon divers',
    'Divers_Percent':'%-Anteil',
    'Publikationen_gesamt':'Publikationen gesamt',
    'Female_Authors': 'davon weibl. Autoren',
    'Anteil female':'%-Anteil',
    'Male_Authors':'davon männl. Autoren',
    'Anteil male':'%-Anteil',
    'Divers_Authors':'davon diverse Autoren',
    'Anteil divers':'%-Anteil'}) 

status_final.to_excel('Results/GLP_Autorenschaft_Gender_Status.xlsx', index=False)
status_final

,Status,Autoren gesamt,davon weiblich,%-Anteil,davon männlich,%-Anteil,davon divers,%-Anteil,Publikationen gesamt,davon weibl. Autoren,%-Anteil,davon männl. Autoren,%-Anteil,davon diverse Autoren,%-Anteil
0,Director,2,0,0,2,100,0,0,31,0,0,31,100,0,0
1,Doctoral Student,35,17,49,18,51,0,0,95,50,53,45,47,0,0
2,Postdoc,12,6,50,6,50,0,0,20,11,55,9,45,0,0
3,Research Group Leader,4,2,50,2,50,0,0,49,13,27,36,73,0,0
4,Senior Researcher,17,6,35,11,65,0,0,155,45,29,110,71,0,0

<hr>

## Hier beginnt die Aufbereitung der Gendertabelle

# ggf. Genre-Zuordnungen für eigenes Institut anpassen

In [60]:
# 📌 Centralized Genre Definitions
genre_config = {
    'book': {
        'genres': ['BOOK'],
        'description': 'Books'
    },
    'article': {
        'genres': ['ARTICLE', 'BOOK_REVIEW', 'EDITORIAL'],
        'description': 'Journal Articles'
    },
    'book_contributions': {
        'genres': [
            'CONTRIBUTION_TO_COLLECTED_EDITION',
            'CONTRIBUTION_TO_ENCYCLOPEDIA',
            'CONTRIBUTION_TO_HANDBOOK',
            'BOOK_ITEM'
        ],
        'description': 'Book Contributions'
    },
    'data': {
        'genres': ['DATA_PUBLICATION'],
        'description': 'Data Publications'
    },
    'thesis': {
        'genres': ['THESIS'],
        'description': 'Theses'
    },
    'blog': {
        'genres': ['BLOG_POST'],
        'description': 'Blog Posts'
    },
    'preprint': {
        'genres': ['PREPRINT'],
        'description': 'Preprints'
    },
    'editions': {
        'genres': ['ISSUE', 'COLLECTED_EDITION', 'HANDBOOK'],
        'description': 'Edited Works'
    },
    'DP': {
        'genres': ['PAPER'],
        'description': 'MPIfG Discussion Papers'
    },
    'others': {
        'genres': ['PAPER'],
        'description': 'Others'
    }
}

## Im Bearbeitungsprozess ien paar Debugging-Aspekte einbauen lassen

In [61]:
for genre_name, config in genre_config.items():
    genre_list = config['genres']
    
    for year in years:
        print(f"\n{'='*60}")
        print(f"Processing: {genre_name.upper()} ({config['description']}) | Year: {year}")
        print(f"{'='*60}")

        # Normalize inputs
        if isinstance(genre_list, str):
            genre_list = [genre_list]
        if isinstance(year, (int,)):
            year_list = [str(year)]
        elif isinstance(year, str):
            year_list = [year]
        else:
            year_list = [str(year)]

        # 📌 Base filtering: Genre and Year (no MPI affiliation filter anymore)
        df_genre = df[df['Genre'].isin(genre_list)].copy()
        print(f"  Debug: df_genre shape after genre filter: {df_genre.shape}")

        if 'Datum' in df_genre.columns:
            print(f"  Debug: 'Datum' column dtype: {df_genre['Datum'].dtype}")
            print(f"  Debug: Unique values in 'Datum' column: {df_genre['Datum'].unique()}")

            # Convert 'Datum' to year string for comparison
            if pd.api.types.is_datetime64_any_dtype(df_genre['Datum']):
                df_genre['Datum_Year_Str'] = df_genre['Datum'].dt.year.astype(str)
            elif pd.api.types.is_numeric_dtype(df_genre['Datum']):
                df_genre['Datum_Year_Str'] = df_genre['Datum'].astype(str)
            else:  # Assume it's a string-like object, try to extract first 4 chars
                df_genre['Datum_Year_Str'] = df_genre['Datum'].astype(str).str[:4]
            
            df_genre_year = df_genre[df_genre['Datum_Year_Str'].isin(year_list)].copy()
            df_genre = df_genre.drop(columns=['Datum_Year_Str'])
        else:
            print("  Debug: 'Datum' column not found in df_genre. Creating empty df_genre_year.")
            df_genre_year = pd.DataFrame()

        print(f"  Debug: df_genre_year shape after year filter: {df_genre_year.shape}")

        # 🔍 Conditional: Only for DP → filter for MPIfG Discussion Paper
        if genre_name == "DP":
            if not df_genre_year.empty and '1101_Quellentitel' in df_genre_year.columns:
                dp_filter = df_genre_year['1101_Quellentitel'].str.contains('MPIfG Discussion Paper', na=False)
                df_genre_year = df_genre_year[dp_filter].copy()
            print(f"  ✅ Filtered DP: {df_genre_year.shape[0]} entries with 'MPIfG Discussion Paper'")

        # 🔍 Conditional: Only for 'other' → add non-MPIfG PAPER entries
        elif genre_name == "other":
            if not df_genre_year.empty and '1101_Quellentitel' in df_genre_year.columns:
                paper_filter = (
                    (df_genre_year['Genre'] == 'PAPER') &
                    (~df_genre_year['1101_Quellentitel'].str.contains('MPIfG Discussion Paper', na=False))
                )
                additional_papers = df_genre_year[paper_filter].copy()
                if not additional_papers.empty:
                    print(f"  ✅ Added {additional_papers.shape[0]} non-MPIfG PAPER entries")
                    df_genre_year = pd.concat([df_genre_year, additional_papers], ignore_index=True)
                else:
                    print("  ❌ No non-MPIfG PAPER entries to add")
            else:
                print("  ❌ No non-MPIfG PAPER entries to add (df_genre_year empty or missing '1101_Quellentitel')")

        # ✅ Create variable name
        var_name = f"df_genre_{year}_{genre_name}"
        globals()[var_name] = df_genre_year.copy()

        # ✅ Print summary
        print(f"  Final shape: {df_genre_year.shape}")
        print(f"  Saved to: {var_name}")

============================================================
Processing: BOOK (Books) | Year: 2023
============================================================
  Debug: df_genre shape after genre filter: (7, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2024 2025 2023]
  Debug: df_genre_year shape after year filter: (1, 13)
  Final shape: (1, 13)
  Saved to: df_genre_2023_book

============================================================
Processing: BOOK (Books) | Year: 2024
============================================================
  Debug: df_genre shape after genre filter: (7, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2024 2025 2023]
  Debug: df_genre_year shape after year filter: (2, 13)
  Final shape: (2, 13)
  Saved to: df_genre_2024_book

============================================================
Processing: BOOK (Books) | Year: 2025
============================================================
  Debug: df_genre shape after genre filter: (7, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2024 2025 2023]
  Debug: df_genre_year shape after year filter: (4, 13)
  Final shape: (4, 13)
  Saved to: df_genre_2025_book

============================================================
Processing: ARTICLE (Journal Articles) | Year: 2023
============================================================
  Debug: df_genre shape after genre filter: (182, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2025 2024 2023]
  Debug: df_genre_year shape after year filter: (50, 13)
  Final shape: (50, 13)
  Saved to: df_genre_2023_article

============================================================
Processing: ARTICLE (Journal Articles) | Year: 2024
============================================================
  Debug: df_genre shape after genre filter: (182, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2025 2024 2023]
  Debug: df_genre_year shape after year filter: (68, 13)
  Final shape: (68, 13)
  Saved to: df_genre_2024_article

============================================================
Processing: ARTICLE (Journal Articles) | Year: 2025
============================================================
  Debug: df_genre shape after genre filter: (182, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2025 2024 2023]
  Debug: df_genre_year shape after year filter: (64, 13)
  Final shape: (64, 13)
  Saved to: df_genre_2025_article

============================================================
Processing: BOOK_CONTRIBUTIONS (Book Contributions) | Year: 2023
============================================================
  Debug: df_genre shape after genre filter: (35, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2024 2025 2023]
  Debug: df_genre_year shape after year filter: (10, 13)
  Final shape: (10, 13)
  Saved to: df_genre_2023_book_contributions

============================================================
Processing: BOOK_CONTRIBUTIONS (Book Contributions) | Year: 2024
============================================================
  Debug: df_genre shape after genre filter: (35, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2024 2025 2023]
  Debug: df_genre_year shape after year filter: (11, 13)
  Final shape: (11, 13)
  Saved to: df_genre_2024_book_contributions

============================================================
Processing: BOOK_CONTRIBUTIONS (Book Contributions) | Year: 2025
============================================================
  Debug: df_genre shape after genre filter: (35, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2024 2025 2023]
  Debug: df_genre_year shape after year filter: (14, 13)
  Final shape: (14, 13)
  Saved to: df_genre_2025_book_contributions

============================================================
Processing: DATA (Data Publications) | Year: 2023
============================================================
  Debug: df_genre shape after genre filter: (26, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2024 2025 2023]
  Debug: df_genre_year shape after year filter: (8, 13)
  Final shape: (8, 13)
  Saved to: df_genre_2023_data

============================================================
Processing: DATA (Data Publications) | Year: 2024
============================================================
  Debug: df_genre shape after genre filter: (26, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2024 2025 2023]
  Debug: df_genre_year shape after year filter: (8, 13)
  Final shape: (8, 13)
  Saved to: df_genre_2024_data

============================================================
Processing: DATA (Data Publications) | Year: 2025
============================================================
  Debug: df_genre shape after genre filter: (26, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2024 2025 2023]
  Debug: df_genre_year shape after year filter: (10, 13)
  Final shape: (10, 13)
  Saved to: df_genre_2025_data

============================================================
Processing: THESIS (Theses) | Year: 2023
============================================================
  Debug: df_genre shape after genre filter: (23, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2023 2025 2024]
  Debug: df_genre_year shape after year filter: (5, 13)
  Final shape: (5, 13)
  Saved to: df_genre_2023_thesis

============================================================
Processing: THESIS (Theses) | Year: 2024
============================================================
  Debug: df_genre shape after genre filter: (23, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2023 2025 2024]
  Debug: df_genre_year shape after year filter: (10, 13)
  Final shape: (10, 13)
  Saved to: df_genre_2024_thesis

============================================================
Processing: THESIS (Theses) | Year: 2025
============================================================
  Debug: df_genre shape after genre filter: (23, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2023 2025 2024]
  Debug: df_genre_year shape after year filter: (8, 13)
  Final shape: (8, 13)
  Saved to: df_genre_2025_thesis

============================================================
Processing: BLOG (Blog Posts) | Year: 2023
============================================================
  Debug: df_genre shape after genre filter: (19, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2024 2025 2023]
  Debug: df_genre_year shape after year filter: (4, 13)
  Final shape: (4, 13)
  Saved to: df_genre_2023_blog

============================================================
Processing: BLOG (Blog Posts) | Year: 2024
============================================================
  Debug: df_genre shape after genre filter: (19, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2024 2025 2023]
  Debug: df_genre_year shape after year filter: (7, 13)
  Final shape: (7, 13)
  Saved to: df_genre_2024_blog

============================================================
Processing: BLOG (Blog Posts) | Year: 2025
============================================================
  Debug: df_genre shape after genre filter: (19, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2024 2025 2023]
  Debug: df_genre_year shape after year filter: (8, 13)
  Final shape: (8, 13)
  Saved to: df_genre_2025_blog

============================================================
Processing: PREPRINT (Preprints) | Year: 2023
============================================================
  Debug: df_genre shape after genre filter: (13, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2024 2023]
  Debug: df_genre_year shape after year filter: (5, 13)
  Final shape: (5, 13)
  Saved to: df_genre_2023_preprint

============================================================
Processing: PREPRINT (Preprints) | Year: 2024
============================================================
  Debug: df_genre shape after genre filter: (13, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2024 2023]
  Debug: df_genre_year shape after year filter: (8, 13)
  Final shape: (8, 13)
  Saved to: df_genre_2024_preprint

============================================================
Processing: PREPRINT (Preprints) | Year: 2025
============================================================
  Debug: df_genre shape after genre filter: (13, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2024 2023]
  Debug: df_genre_year shape after year filter: (0, 13)
  Final shape: (0, 13)
  Saved to: df_genre_2025_preprint

============================================================
Processing: EDITIONS (Edited Works) | Year: 2023
============================================================
  Debug: df_genre shape after genre filter: (13, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2025 2024 2023]
  Debug: df_genre_year shape after year filter: (1, 13)
  Final shape: (1, 13)
  Saved to: df_genre_2023_editions

============================================================
Processing: EDITIONS (Edited Works) | Year: 2024
============================================================
  Debug: df_genre shape after genre filter: (13, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2025 2024 2023]
  Debug: df_genre_year shape after year filter: (7, 13)
  Final shape: (7, 13)
  Saved to: df_genre_2024_editions

============================================================
Processing: EDITIONS (Edited Works) | Year: 2025
============================================================
  Debug: df_genre shape after genre filter: (13, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2025 2024 2023]
  Debug: df_genre_year shape after year filter: (5, 13)
  Final shape: (5, 13)
  Saved to: df_genre_2025_editions

============================================================
Processing: DP (MPIfG Discussion Papers) | Year: 2023
============================================================
  Debug: df_genre shape after genre filter: (32, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2025 2023 2024]
  Debug: df_genre_year shape after year filter: (14, 13)
  ✅ Filtered DP: 5 entries with 'MPIfG Discussion Paper'
  Final shape: (5, 13)
  Saved to: df_genre_2023_DP

============================================================
Processing: DP (MPIfG Discussion Papers) | Year: 2024
============================================================
  Debug: df_genre shape after genre filter: (32, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2025 2023 2024]
  Debug: df_genre_year shape after year filter: (10, 13)
  ✅ Filtered DP: 5 entries with 'MPIfG Discussion Paper'
  Final shape: (5, 13)
  Saved to: df_genre_2024_DP

============================================================
Processing: DP (MPIfG Discussion Papers) | Year: 2025
============================================================
  Debug: df_genre shape after genre filter: (32, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2025 2023 2024]
  Debug: df_genre_year shape after year filter: (8, 13)
  ✅ Filtered DP: 1 entries with 'MPIfG Discussion Paper'
  Final shape: (1, 13)
  Saved to: df_genre_2025_DP

============================================================
Processing: OTHERS (Others) | Year: 2023
============================================================
  Debug: df_genre shape after genre filter: (32, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2025 2023 2024]
  Debug: df_genre_year shape after year filter: (14, 13)
  Final shape: (14, 13)
  Saved to: df_genre_2023_others

============================================================
Processing: OTHERS (Others) | Year: 2024
============================================================
  Debug: df_genre shape after genre filter: (32, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2025 2023 2024]
  Debug: df_genre_year shape after year filter: (10, 13)
  Final shape: (10, 13)
  Saved to: df_genre_2024_others

============================================================
Processing: OTHERS (Others) | Year: 2025
============================================================
  Debug: df_genre shape after genre filter: (32, 12)
  Debug: 'Datum' column dtype: int64
  Debug: Unique values in 'Datum' column: [2025 2023 2024]
  Debug: df_genre_year shape after year filter: (8, 13)
  Final shape: (8, 13)
  Saved to: df_genre_2025_others

In [62]:
# Zusammenfügen der einzelnen Auswertungen zu einer Tabelle

# 📌 Step 1: Collect all genre-year DataFrames from globals()
matched_dfs = {
    name: value for name, value in globals().items()
    if name.startswith("df_genre_") and isinstance(value, pd.DataFrame)
}

print(f"✅ Found {len(matched_dfs)} genre-year DataFrames.")

# 📌 Step 2: Prepare the summary list
summary_data = []

# 📌 Step 3: Loop through each DataFrame and extract summary stats
for var_name, df in matched_dfs.items():
    print(f"\n🔍 Processing: {var_name}")

    # Extract year and genre from variable name: e.g., df_genre_2025_book
    parts = var_name.replace("df_genre_", "").split("_")
    if len(parts) < 2:
        print(f"  ❌ Skipping malformed name: {var_name}")
        continue
    year = parts[0]
    genre_name = "_".join(parts[1:])

    # Get description from config
    description = genre_config.get(genre_name, {}).get('description', 'Unknown')

    # 🔍 ✅ Step 3.1: Check if 'Gender' column exists and is cleaned
    if 'Gender' not in df.columns:
        print(f"  ❌ No 'Gender' column in {var_name} — skipping.")
        continue

    # 🔍 ✅ Step 3.2: Ensure Gender is cleaned (e.g., 'Male', 'Female', 'Divers', 'Missing')
    # If not, clean it now
    if not df['Gender'].isin(['Male', 'Female', 'Divers', 'Missing']).all():
        print(f"  ⚠️ Cleaning Gender column in {var_name}...")
        df_clean = df.copy()
        df_clean['Gender'] = df_clean['Gender'].replace({
            'M': 'Male',
            'F': 'Female',
            'male': 'Male',
            'female': 'Female',
            'Diverse': 'Divers',
            'Other': 'Divers',
            'Non-binary': 'Divers',
            'Non Binary': 'Divers',
            '': 'Missing',
            np.nan: 'Missing'
        })
    else:
        df_clean = df  # Already cleaned

    # 🔍 ✅ Step 3.3: Count gender values
    gender_counts = df_clean['Gender'].value_counts().to_dict()
    male = gender_counts.get('Male', 0)
    female = gender_counts.get('Female', 0)
    divers = gender_counts.get('Divers', 0)
    missing = gender_counts.get('Missing', 0)

    # 🔍 ✅ Step 3.4: Total count
    total = len(df_clean)

    # 🔍 ✅ Step 3.5: Calculate percentages (safe division)
    male_pct = (male / total) * 100 if total > 0 else 0
    female_pct = (female / total) * 100 if total > 0 else 0
    divers_pct = (divers / total) * 100 if total > 0 else 0

    # 🔍 ✅ Step 3.6: Print debug info
    print(f"  ✅ Total: {total}, Male: {male}, Female: {female}, Divers: {divers}, Missing: {missing}")
    print(f"  ✅ Percentages: {male_pct:.1f}%, {female_pct:.1f}%, {divers_pct:.1f}%")

    # Append to summary
    summary_data.append({
        'Year': year,
        'Genre': genre_name,
        'Description': description,
        'Total': total,
        'Male': male,
        'Female': female,
        'Divers': divers,
        'Missing': missing,
        'Male %': round(male_pct, 1),
        'Female %': round(female_pct, 1),
        'Divers %': round(divers_pct, 1)
    })

# 📌 Step 4: Create the master summary DataFrame
master_summary = pd.DataFrame(summary_data)

# 📌 Step 5: Sort and reset index
master_summary = master_summary.sort_values(['Year', 'Genre']).reset_index(drop=True)

# 📌 Step 6: Add yearly totals (with proper rounding)
yearly_totals = master_summary.groupby('Year', as_index=False)[['Total', 'Male', 'Female', 'Divers']].sum()
yearly_totals['Genre'] = 'Total'
yearly_totals['Description'] = 'Yearly Total'
yearly_totals['Missing'] = 0
yearly_totals['Male %'] = (yearly_totals['Male'] / yearly_totals['Total']) * 100
yearly_totals['Female %'] = (yearly_totals['Female'] / yearly_totals['Total']) * 100
yearly_totals['Divers %'] = (yearly_totals['Divers'] / yearly_totals['Total']) * 100
yearly_totals = yearly_totals.round(1)

# Append totals
master_summary = pd.concat([master_summary, yearly_totals], ignore_index=True)

✅ Found 31 genre-year DataFrames.

🔍 Processing: df_genre_year
  ❌ Skipping malformed name: df_genre_year

🔍 Processing: df_genre_2023_book
  ⚠️ Cleaning Gender column in df_genre_2023_book...
  ✅ Total: 1, Male: 1, Female: 0, Divers: 0, Missing: 0
  ✅ Percentages: 100.0%, 0.0%, 0.0%

🔍 Processing: df_genre_2024_book
  ⚠️ Cleaning Gender column in df_genre_2024_book...
  ✅ Total: 2, Male: 2, Female: 0, Divers: 0, Missing: 0
  ✅ Percentages: 100.0%, 0.0%, 0.0%

🔍 Processing: df_genre_2025_book
  ⚠️ Cleaning Gender column in df_genre_2025_book...
  ✅ Total: 4, Male: 3, Female: 1, Divers: 0, Missing: 0
  ✅ Percentages: 75.0%, 25.0%, 0.0%

🔍 Processing: df_genre_2023_article
  ⚠️ Cleaning Gender column in df_genre_2023_article...
  ✅ Total: 50, Male: 34, Female: 16, Divers: 0, Missing: 0
  ✅ Percentages: 68.0%, 32.0%, 0.0%

🔍 Processing: df_genre_2024_article
  ⚠️ Cleaning Gender column in df_genre_2024_article...
  ✅ Total: 68, Male: 46, Female: 22, Divers: 0, Missing: 0
  ✅ Percentages: 67.6%, 32.4%, 0.0%

🔍 Processing: df_genre_2025_article
  ⚠️ Cleaning Gender column in df_genre_2025_article...
  ✅ Total: 64, Male: 43, Female: 21, Divers: 0, Missing: 0
  ✅ Percentages: 67.2%, 32.8%, 0.0%

🔍 Processing: df_genre_2023_book_contributions
  ⚠️ Cleaning Gender column in df_genre_2023_book_contributions...
  ✅ Total: 10, Male: 8, Female: 2, Divers: 0, Missing: 0
  ✅ Percentages: 80.0%, 20.0%, 0.0%

🔍 Processing: df_genre_2024_book_contributions
  ⚠️ Cleaning Gender column in df_genre_2024_book_contributions...
  ✅ Total: 11, Male: 11, Female: 0, Divers: 0, Missing: 0
  ✅ Percentages: 100.0%, 0.0%, 0.0%

🔍 Processing: df_genre_2025_book_contributions
  ⚠️ Cleaning Gender column in df_genre_2025_book_contributions...
  ✅ Total: 14, Male: 6, Female: 8, Divers: 0, Missing: 0
  ✅ Percentages: 42.9%, 57.1%, 0.0%

🔍 Processing: df_genre_2023_data
  ⚠️ Cleaning Gender column in df_genre_2023_data...
  ✅ Total: 8, Male: 3, Female: 5, Divers: 0, Missing: 0
  ✅ Percentages: 37.5%, 62.5%, 0.0%

🔍 Processing: df_genre_2024_data
  ⚠️ Cleaning Gender column in df_genre_2024_data...
  ✅ Total: 8, Male: 7, Female: 1, Divers: 0, Missing: 0
  ✅ Percentages: 87.5%, 12.5%, 0.0%

🔍 Processing: df_genre_2025_data
  ⚠️ Cleaning Gender column in df_genre_2025_data...
  ✅ Total: 10, Male: 2, Female: 8, Divers: 0, Missing: 0
  ✅ Percentages: 20.0%, 80.0%, 0.0%

🔍 Processing: df_genre_2023_thesis
  ⚠️ Cleaning Gender column in df_genre_2023_thesis...
  ✅ Total: 5, Male: 3, Female: 2, Divers: 0, Missing: 0
  ✅ Percentages: 60.0%, 40.0%, 0.0%

🔍 Processing: df_genre_2024_thesis
  ⚠️ Cleaning Gender column in df_genre_2024_thesis...
  ✅ Total: 10, Male: 4, Female: 6, Divers: 0, Missing: 0
  ✅ Percentages: 40.0%, 60.0%, 0.0%

🔍 Processing: df_genre_2025_thesis
  ⚠️ Cleaning Gender column in df_genre_2025_thesis...
  ✅ Total: 8, Male: 4, Female: 4, Divers: 0, Missing: 0
  ✅ Percentages: 50.0%, 50.0%, 0.0%

🔍 Processing: df_genre_2023_blog
  ⚠️ Cleaning Gender column in df_genre_2023_blog...
  ✅ Total: 4, Male: 4, Female: 0, Divers: 0, Missing: 0
  ✅ Percentages: 100.0%, 0.0%, 0.0%

🔍 Processing: df_genre_2024_blog
  ⚠️ Cleaning Gender column in df_genre_2024_blog...
  ✅ Total: 7, Male: 2, Female: 5, Divers: 0, Missing: 0
  ✅ Percentages: 28.6%, 71.4%, 0.0%

🔍 Processing: df_genre_2025_blog
  ⚠️ Cleaning Gender column in df_genre_2025_blog...
  ✅ Total: 8, Male: 4, Female: 4, Divers: 0, Missing: 0
  ✅ Percentages: 50.0%, 50.0%, 0.0%

🔍 Processing: df_genre_2023_preprint
  ⚠️ Cleaning Gender column in df_genre_2023_preprint...
  ✅ Total: 5, Male: 5, Female: 0, Divers: 0, Missing: 0
  ✅ Percentages: 100.0%, 0.0%, 0.0%

🔍 Processing: df_genre_2024_preprint
  ⚠️ Cleaning Gender column in df_genre_2024_preprint...
  ✅ Total: 8, Male: 8, Female: 0, Divers: 0, Missing: 0
  ✅ Percentages: 100.0%, 0.0%, 0.0%

🔍 Processing: df_genre_2025_preprint
  ✅ Total: 0, Male: 0, Female: 0, Divers: 0, Missing: 0
  ✅ Percentages: 0.0%, 0.0%, 0.0%

🔍 Processing: df_genre_2023_editions
  ⚠️ Cleaning Gender column in df_genre_2023_editions...
  ✅ Total: 1, Male: 1, Female: 0, Divers: 0, Missing: 0
  ✅ Percentages: 100.0%, 0.0%, 0.0%

🔍 Processing: df_genre_2024_editions
  ⚠️ Cleaning Gender column in df_genre_2024_editions...
  ✅ Total: 7, Male: 5, Female: 2, Divers: 0, Missing: 0
  ✅ Percentages: 71.4%, 28.6%, 0.0%

🔍 Processing: df_genre_2025_editions
  ⚠️ Cleaning Gender column in df_genre_2025_editions...
  ✅ Total: 5, Male: 3, Female: 2, Divers: 0, Missing: 0
  ✅ Percentages: 60.0%, 40.0%, 0.0%

🔍 Processing: df_genre_2023_DP
  ⚠️ Cleaning Gender column in df_genre_2023_DP...
  ✅ Total: 5, Male: 3, Female: 2, Divers: 0, Missing: 0
  ✅ Percentages: 60.0%, 40.0%, 0.0%

🔍 Processing: df_genre_2024_DP
  ⚠️ Cleaning Gender column in df_genre_2024_DP...
  ✅ Total: 5, Male: 4, Female: 1, Divers: 0, Missing: 0
  ✅ Percentages: 80.0%, 20.0%, 0.0%

🔍 Processing: df_genre_2025_DP
  ⚠️ Cleaning Gender column in df_genre_2025_DP...
  ✅ Total: 1, Male: 0, Female: 1, Divers: 0, Missing: 0
  ✅ Percentages: 0.0%, 100.0%, 0.0%

🔍 Processing: df_genre_2023_others
  ⚠️ Cleaning Gender column in df_genre_2023_others...
  ✅ Total: 14, Male: 10, Female: 4, Divers: 0, Missing: 0
  ✅ Percentages: 71.4%, 28.6%, 0.0%

🔍 Processing: df_genre_2024_others
  ⚠️ Cleaning Gender column in df_genre_2024_others...
  ✅ Total: 10, Male: 8, Female: 2, Divers: 0, Missing: 0
  ✅ Percentages: 80.0%, 20.0%, 0.0%

🔍 Processing: df_genre_2025_others
  ⚠️ Cleaning Gender column in df_genre_2025_others...
  ✅ Total: 8, Male: 4, Female: 4, Divers: 0, Missing: 0
  ✅ Percentages: 50.0%, 50.0%, 0.0%

In [ ]:
# master_summary  #wenn man es sich ansehen möchte, aktivieren

In [65]:
df_genre_2025_DP

,Genre,Nachname,Vorname,Name,Cone,Affiliation,1101_Quellentitel,Datum,ItemID,Gender,Status,Item_seq,Datum_Year_Str
1084,PAPER,Soer,Elizabeth,Elizabeth Soer,CONE,International Max Planck Research School on th...,MPIfG Discussion Paper,2025,item_3644198,female,Doctoral Student,1,2025

Achtung: Spalte "Total" zählt alle MPIfG-Autor*innen, nicht die Anzahl der Titel, aber ist ja logisch, um die Geschlechteranteile auszurechnen

In [63]:
final_summary = master_summary[['Year', 'Description', 'Male', 'Female', 'Divers', 'Female %']] # auf relevante Spalten reduzieren

final_summary.to_excel("Results/GLP_summary_nach_Genre.xlsx", index=False)
final_summary

# das kann dann in Excel noch etwas in Form gebracht werden für die Jahre

    Year              Description  Male  Female  Divers  Female %
0   2023  MPIfG Discussion Papers     3       2       0      40.0
1   2023         Journal Articles    34      16       0      32.0
2   2023               Blog Posts     4       0       0       0.0
3   2023                    Books     1       0       0       0.0
4   2023       Book Contributions     8       2       0      20.0
5   2023        Data Publications     3       5       0      62.5
6   2023             Edited Works     1       0       0       0.0
7   2023                   Others    10       4       0      28.6
8   2023                Preprints     5       0       0       0.0
9   2023                   Theses     3       2       0      40.0
10  2024  MPIfG Discussion Papers     4       1       0      20.0
11  2024         Journal Articles    46      22       0      32.4
12  2024               Blog Posts     2       5       0      71.4
13  2024                    Books     2       0       0       0.0
14  2024       Book Contributions    11       0       0       0.0
15  2024        Data Publications     7       1       0      12.5
16  2024             Edited Works     5       2       0      28.6
17  2024                   Others     8       2       0      20.0
18  2024                Preprints     8       0       0       0.0
19  2024                   Theses     4       6       0      60.0
20  2025  MPIfG Discussion Papers     0       1       0     100.0
21  2025         Journal Articles    43      21       0      32.8
22  2025               Blog Posts     4       4       0      50.0
23  2025                    Books     3       1       0      25.0
24  2025       Book Contributions     6       8       0      57.1
25  2025        Data Publications     2       8       0      80.0
26  2025             Edited Works     3       2       0      40.0
27  2025                   Others     4       4       0      50.0
28  2025                Preprints     0       0       0       0.0
29  2025                   Theses     4       4       0      50.0
30  2023             Yearly Total    72      31       0      30.1
31  2024             Yearly Total    97      39       0      28.7
32  2025             Yearly Total    69      53       0      43.4